apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    name: appPod
spec:
  containers:
  - name: appcontainer
    image: ghcr.io/ccc909/proiect_tt:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
