name: 'Deploy'
description: 'Deploy to K8S'
runs:
    using: 'composite'
    steps:
        - name: Install Minikube
          run: |
            curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
            sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
          shell: bash
        - name: Start Minikube
          run: minikube start
          shell: bash
        - name: Deploy Image
          run: |
            minikube kubectl create sa default
            minikube kubectl -- apply --filename pod.yml
          shell: bash